### ISSUE TITLE
Select not working anymore in 5.3.X

### ISSUE THREAD

**Issue by mparisot-antescofo** [rism-digital/verovio#4077]
**Describe the problem**
Hello, I am using the Javascript implementation and after updating from 5.2.0 to 5.3.0 and 5.3.1 the calls to `redoLayout()`  fails with the error: `RuntimeError: null function or function signature mismatch`

**To Reproduce**
1. Initialize the toolkit
2. Change the options ?
3. call toolkit.redoLayoyt()

**Expected behavior**
No error and the score rendering with the new options

**Verovio information**
 - Tried with both 5.3.0 and 5.3.1
 - Javascript lib

**Environment information (as appropriate)**
 - locally on MacOs and on our netlify host
 - Chrome

The full stack if needed:
```
Uncaught RuntimeError: null function or function signature mismatch
    at 0150836e:0x2680c0
    at 0150836e:0x17e984
    at 0150836e:0x261545
    at 0150836e:0x1e977a
    at 0150836e:0x692f
    at 0150836e:0x6a52
    at 0150836e:0x6a52
    at 0150836e:0x5b3b7
    at 0150836e:0x209de9
    at ccall (verovio-toolkit-wasm.js:14:7415828)
    at verovio-toolkit-wasm.js:14:7416197
    at Proxy.<anonymous> (verovio-toolkit-wasm.js:26:66)
    at VerovioToolkitDefaultModule.redoLayout (verovio-toolkit-wasm.js:297:21)
````

and the one using https://www.verovio.org/javascript/latest/verovio-toolkit.js instead of WASM:
```
verovio-toolkit.js:31 Uncaught TypeError: za[J[((J[(b >> 2)] + 48) >> 2)]] is not a function
    at Array.Zsa (verovio-toolkit.js:31:48657)
    at wO (verovio-toolkit.js:29:25650)
    at Array.Tna (verovio-toolkit.js:45:18305)
    at Array.n2 (verovio-toolkit.js:44:12278)
    at bb (verovio-toolkit.js:33:37109)
    at bb (verovio-toolkit.js:33:37729)
    at bb (verovio-toolkit.js:33:37729)
    at Lp (verovio-toolkit.js:27:941126)
    at Z8 (verovio-toolkit.js:29:124381)
    at ccall (verovio-toolkit.js:54:65349)
    at verovio-toolkit.js:54:65718
    at Proxy.<anonymous> (verovio-toolkit.js:66:66)
    at VerovioToolkitDefaultModule.redoLayout (verovio-toolkit.js:337:21)
```

Let me know if anything is missing

Thank you

**Comment by lpugin** [comment]
`redoLayout` is used in many places in the https://editor.verovio.org/ (e.g., changing the zoom, adjusting the size of the window, or changing the font in the settings), and all these seem to be working.

Can you narrow it down to a minimal example that can be reproduced?

**Comment by mparisot-antescofo** [comment]
Thank you for the quick reply. I won't have time to take a deeper look and try to isolate things more today but I'll try to do so tomorrow or at worse early next week as I am off the rest of the week.

**Comment by lpugin** [comment]
I pushed a [fix](https://github.com/rism-digital/verovio/commit/b2bb748352d1054ffe9d1020a5a0084c9993439e) to develop. If testing shows that it is fixed I'll make a patch release

**Comment by lpugin** [comment]
The [documentation example](https://book.verovio.org/tutorials/content-selection.html) is now working again, so I'll make a release.

**Comment by mparisot-antescofo** [comment]
I confirm that the 5.3.0 works for me thanks a lot for the quick fix!
